In [2]:
import numpy as np

In [3]:
simple_list=[1,2,3,4]
np.array(simple_list)

array([1, 2, 3, 4])

In [4]:
list2=[1,2,3],[4,5,6],[7,8,9]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,100)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(1,14,3)

array([ 1,  4,  7, 10, 13])

In [9]:
np.arange(10,1)

array([], dtype=int32)

In [11]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
np.random.rand(3,5)

array([[0.51249915, 0.4439775 , 0.4526429 , 0.57850138, 0.84458275],
       [0.39729918, 0.46549272, 0.88190551, 0.05012513, 0.29523462],
       [0.34410569, 0.42957791, 0.461008  , 0.27925375, 0.47148734]])

In [26]:
np.random.randn(3,5)

array([[ 0.37893036, -1.64111223, -1.89862631,  1.11400875,  0.0031118 ],
       [-1.19365744, -0.74379062,  0.13556148,  1.27745724, -0.34653427],
       [ 0.21825755,  1.52664079,  2.10300382,  2.25107174,  0.76234548]])

In [32]:
np.random.randint(3,5)

4

In [33]:
np.random.randint(1,25,100)

array([13, 12, 13, 22, 21, 19,  9, 11, 17,  1,  8, 12, 11, 24, 14,  9,  9,
        4, 13,  5,  5, 17,  2, 13, 15, 15, 23, 10,  7, 22, 21,  5,  7,  7,
       12, 24,  9, 14, 17, 18, 13, 20,  8, 13,  7, 20, 13, 17,  1, 11, 21,
       15, 21,  8, 23,  6, 17,  5,  4,  9,  1,  4, 23,  8,  7,  7,  4, 19,
        6, 16, 20, 16, 11,  3, 24, 10,  4, 12,  7, 23, 15, 10,  2, 23,  5,
       13, 18, 10, 20, 10,  5, 15,  1,  1,  1, 11, 12,  3, 19, 18])

In [34]:
sample_array=np.arange(30)

In [35]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
sample_array.reshape(3,6)

ValueError: cannot reshape array of size 30 into shape (3,6)

In [39]:
sample_array.max()

29

In [40]:
sample_array.min()

0

In [41]:
sample_array.mean()

14.5

In [42]:
sample_array.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [43]:
np.median(sample_array)

14.5

In [44]:
sample_array.var()

74.91666666666667

In [45]:
sample_array.std()

8.65544144839919

In [46]:
sample_array.argmax()

29

In [47]:
sample_array.argmin()

0

In [50]:
sample_array[0]

0

In [51]:
sample_array[5]

5

In [52]:
sample_array[0:4]

array([0, 1, 2, 3])

In [53]:
sample_array[0:4]=100
sample_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [56]:
sample_matrix=np.array([[1,56,32,41],[34,65,98,26],[10,79,42,67]])

In [57]:
sample_matrix

array([[ 1, 56, 32, 41],
       [34, 65, 98, 26],
       [10, 79, 42, 67]])

In [58]:
sample_matrix[1,2]

98

In [59]:
sample_matrix[2]

array([10, 79, 42, 67])

In [60]:
sample_matrix[2,:]

array([10, 79, 42, 67])

In [61]:
sample_matrix[2,2:4]

array([42, 67])

In [62]:
sample_matrix[2,2:]

array([42, 67])

In [65]:
sample_matrix[:,-1:-3]

array([], shape=(3, 0), dtype=int32)

In [66]:
sample_matrix

array([[ 1, 56, 32, 41],
       [34, 65, 98, 26],
       [10, 79, 42, 67]])

In [67]:
sample_matrix[:,2:0:-1]

array([[32, 56],
       [98, 65],
       [42, 79]])

In [69]:
sample_matrix[:,(2,1)]

array([[32, 56],
       [98, 65],
       [42, 79]])

In [ ]:
# Create an array from 1 to 10
# Create an array of 10 zeros of int datatype
# Create 5x5 identity matrix
# Print numbers :50,48,46,.......0
# Create an array and find squareroot,log,exponential,sin,cos,tan,square for the same
# Create random numbers ranging from 0 to 1 of shape 3 and 4 and try to round it off to two decimal places